version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile.prod
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
    command: ['npm', 'run', 'start']
