# Chọn base image cho môi trường sản xuất
FROM node:20.09 AS prod

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --only=production

COPY . .

RUN npm run build

EXPOSE 4000


CMD ["npm", "run", "start"]
